# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\tim.common\"6\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t*I\n\x07\x43hannel\x12\x17\n\x13\x43HANNEL_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x43HANNEL_CONTROL\x10\x01\x12\x10\n\x0c\x43HANNEL_FILE\x10\x02*}\n\x0e\x44\x65liveryStatus\x12\x18\n\x14\x44\x45LIVERY_UNSPECIFIED\x10\x00\x12\x11\n\rDELIVERY_SENT\x10\x01\x12\x16\n\x12\x44\x45LIVERY_DELIVERED\x10\x02\x12\x11\n\rDELIVERY_READ\x10\x03\x12\x13\n\x0f\x44\x45LIVERY_FAILED\x10\x04*]\n\x0bMessageType\x12\x13\n\x0fMSG_UNSPECIFIED\x10\x00\x12\x0c\n\x08MSG_TEXT\x10\x01\x12\r\n\tMSG_IMAGE\x10\x02\x12\x0c\n\x08MSG_FILE\x10\x03\x12\x0e\n\nMSG_SYSTEM\x10\x04*a\n\x10\x43onversationType\x12\x1c\n\x18\x43ONVERSATION_UNSPECIFIED\x10\x00\x12\x17\n\x13\x43ONVERSATION_DIRECT\x10\x01\x12\x16\n\x12\x43ONVERSATION_GROUP\x10\x02*o\n\x15\x46ileTransferDirection\x12\x1e\n\x1a\x46ILE_DIRECTION_UNSPECIFIED\x10\x00\x12\x19\n\x15\x46ILE_DIRECTION_UPLOAD\x10\x01\x12\x1b\n\x17\x46ILE_DIRECTION_DOWNLOAD\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNEL']._serialized_start=83
  _globals['_CHANNEL']._serialized_end=156
  _globals['_DELIVERYSTATUS']._serialized_start=158
  _globals['_DELIVERYSTATUS']._serialized_end=283
  _globals['_MESSAGETYPE']._serialized_start=285
  _globals['_MESSAGETYPE']._serialized_end=378
  _globals['_CONVERSATIONTYPE']._serialized_start=380
  _globals['_CONVERSATIONTYPE']._serialized_end=477
  _globals['_FILETRANSFERDIRECTION']._serialized_start=479
  _globals['_FILETRANSFERDIRECTION']._serialized_end=590
  _globals['_ERROR']._serialized_start=27
  _globals['_ERROR']._serialized_end=81
# @@protoc_insertion_point(module_scope)
