# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: conversation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'conversation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63onversation.proto\x12\x0fim.conversation\x1a\x0c\x63ommon.proto\"z\n\x12\x43reateConversation\x12\x16\n\x0e\x63lient_conv_id\x18\x01 \x01(\t\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.im.common.ConversationType\x12\x12\n\nmember_ids\x18\x03 \x03(\t\x12\r\n\x05title\x18\x04 \x01(\t\"9\n\nAddMembers\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x12\n\nmember_ids\x18\x02 \x03(\t\"<\n\rRemoveMembers\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x12\n\nmember_ids\x18\x02 \x03(\t\",\n\x11LeaveConversation\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\"+\n\x10JoinConversation\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\"<\n\x12RenameConversation\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\"\xb7\x01\n\x13\x43onversationUpdated\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x15\n\rupdated_at_ms\x18\x03 \x01(\x03\x12\r\n\x05title\x18\x04 \x01(\t\x12)\n\x04type\x18\x05 \x01(\x0e\x32\x1b.im.common.ConversationType\x12\x10\n\x08owner_id\x18\x06 \x01(\t\x12\x12\n\nmember_ids\x18\x07 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'conversation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECONVERSATION']._serialized_start=53
  _globals['_CREATECONVERSATION']._serialized_end=175
  _globals['_ADDMEMBERS']._serialized_start=177
  _globals['_ADDMEMBERS']._serialized_end=234
  _globals['_REMOVEMEMBERS']._serialized_start=236
  _globals['_REMOVEMEMBERS']._serialized_end=296
  _globals['_LEAVECONVERSATION']._serialized_start=298
  _globals['_LEAVECONVERSATION']._serialized_end=342
  _globals['_JOINCONVERSATION']._serialized_start=344
  _globals['_JOINCONVERSATION']._serialized_end=387
  _globals['_RENAMECONVERSATION']._serialized_start=389
  _globals['_RENAMECONVERSATION']._serialized_end=449
  _globals['_CONVERSATIONUPDATED']._serialized_start=452
  _globals['_CONVERSATIONUPDATED']._serialized_end=635
# @@protoc_insertion_point(module_scope)
