# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nfile.proto\x12\x07im.file\x1a\x0c\x63ommon.proto\"\xe7\x01\n\x08\x46ileInit\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63lient_file_id\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x11\n\tfile_size\x18\x04 \x01(\x04\x12\x0e\n\x06sha256\x18\x05 \x01(\t\x12\x33\n\tdirection\x18\x06 \x01(\x0e\x32 .im.common.FileTransferDirection\x12\x15\n\rresume_offset\x18\x07 \x01(\x04\x12\x10\n\x08priority\x18\x08 \x01(\r\x12\x16\n\x0esource_file_id\x18\t \x01(\t\"Y\n\nFileFinish\x12\x0f\n\x07\x66ile_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x19\n\x11transferred_bytes\x18\x03 \x01(\x04\x12\x0e\n\x06sha256\x18\x04 \x01(\t\"\x9a\x02\n\x0b\x46ileUpdated\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x03 \x01(\t\x12\x19\n\x11transferred_bytes\x18\x04 \x01(\x04\x12\x11\n\tcompleted\x18\x05 \x01(\x08\x12\x0f\n\x07version\x18\x06 \x01(\x04\x12\x15\n\rupdated_at_ms\x18\x07 \x01(\x03\x12\x11\n\tfile_size\x18\x08 \x01(\x04\x12\x0e\n\x06sha256\x18\t \x01(\t\x12\x33\n\tdirection\x18\n \x01(\x0e\x32 .im.common.FileTransferDirection\x12\x0e\n\x06status\x18\x0b \x01(\t\x12\x11\n\tfile_name\x18\x0c \x01(\t\"5\n\nFileCancel\x12\x16\n\x0e\x63lient_file_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66ile_id\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEINIT']._serialized_start=38
  _globals['_FILEINIT']._serialized_end=269
  _globals['_FILEFINISH']._serialized_start=271
  _globals['_FILEFINISH']._serialized_end=360
  _globals['_FILEUPDATED']._serialized_start=363
  _globals['_FILEUPDATED']._serialized_end=645
  _globals['_FILECANCEL']._serialized_start=647
  _globals['_FILECANCEL']._serialized_end=700
# @@protoc_insertion_point(module_scope)
