# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\nim.message\x1a\x0c\x63ommon.proto\"\x9d\x01\n\x0bSendMessage\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x15\n\rclient_msg_id\x18\x02 \x01(\t\x12$\n\x04type\x18\x03 \x01(\x0e\x32\x16.im.common.MessageType\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\x0c\x12\x11\n\tburn_mode\x18\n \x01(\r\x12\x14\n\x0c\x62urn_ttl_sec\x18\x0b \x01(\r\"\x8c\x02\n\x07Message\x12\x12\n\nmessage_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x11\n\tsender_id\x18\x03 \x01(\t\x12\x15\n\rclient_msg_id\x18\x04 \x01(\t\x12\x0b\n\x03seq\x18\x05 \x01(\x04\x12$\n\x04type\x18\x06 \x01(\x0e\x32\x16.im.common.MessageType\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\x0c\x12\x15\n\rcreated_at_ms\x18\x08 \x01(\x03\x12\x10\n\x08recalled\x18\t \x01(\x08\x12\x14\n\x0cunread_count\x18\n \x01(\r\x12\x11\n\tburn_mode\x18\x0b \x01(\r\x12\x14\n\x0c\x62urn_ttl_sec\x18\x0c \x01(\r\"F\n\x0bMessagePush\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12%\n\x08messages\x18\x02 \x03(\x0b\x32\x13.im.message.Message\"t\n\x03\x41\x63k\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05\x12\x0f\n\x07message\x18\x04 \x01(\t\x12\x11\n\tentity_id\x18\x05 \x01(\t\x12\x16\n\x0eserver_time_ms\x18\x06 \x01(\x03\"r\n\x07Receipt\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x15\n\rlast_read_seq\x18\x03 \x01(\x04\x12\x12\n\nread_at_ms\x18\x04 \x01(\x03\x12\x11\n\treader_id\x18\x05 \x01(\t\"k\n\x06Recall\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x17\n\x0f\x63onversation_id\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\t\x12\r\n\x05ts_ms\x18\x04 \x01(\x03\x12\x13\n\x0boperator_id\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGE']._serialized_start=44
  _globals['_SENDMESSAGE']._serialized_end=201
  _globals['_MESSAGE']._serialized_start=204
  _globals['_MESSAGE']._serialized_end=472
  _globals['_MESSAGEPUSH']._serialized_start=474
  _globals['_MESSAGEPUSH']._serialized_end=544
  _globals['_ACK']._serialized_start=546
  _globals['_ACK']._serialized_end=662
  _globals['_RECEIPT']._serialized_start=664
  _globals['_RECEIPT']._serialized_end=778
  _globals['_RECALL']._serialized_start=780
  _globals['_RECALL']._serialized_end=887
# @@protoc_insertion_point(module_scope)
