# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sync.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import conversation_pb2 as conversation__pb2
from . import file_pb2 as file__pb2
from . import message_pb2 as message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsync.proto\x12\x07im.sync\x1a\x12\x63onversation.proto\x1a\nfile.proto\x1a\rmessage.proto\"i\n\x0bSyncRequest\x12\x15\n\rglobal_cursor\x18\x01 \x01(\x04\x12\r\n\x05limit\x18\x02 \x01(\r\x12\x17\n\x0f\x63onversation_id\x18\x03 \x01(\t\x12\x1b\n\x13\x63onversation_cursor\x18\x04 \x01(\x04\"\x8f\x02\n\tSyncEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12&\n\x07message\x18\n \x01(\x0b\x32\x13.im.message.MessageH\x00\x12$\n\x06recall\x18\x0b \x01(\x0b\x32\x12.im.message.RecallH\x00\x12&\n\x07receipt\x18\x0c \x01(\x0b\x32\x13.im.message.ReceiptH\x00\x12\x44\n\x14\x63onversation_updated\x18\r \x01(\x0b\x32$.im.conversation.ConversationUpdatedH\x00\x12,\n\x0c\x66ile_updated\x18\x0e \x01(\x0b\x32\x14.im.file.FileUpdatedH\x00\x42\x06\n\x04\x62ody\"_\n\x0cSyncResponse\x12\x19\n\x11new_global_cursor\x18\x01 \x01(\x04\x12\"\n\x06\x65vents\x18\x02 \x03(\x0b\x32\x12.im.sync.SyncEvent\x12\x10\n\x08has_more\x18\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYNCREQUEST']._serialized_start=70
  _globals['_SYNCREQUEST']._serialized_end=175
  _globals['_SYNCEVENT']._serialized_start=178
  _globals['_SYNCEVENT']._serialized_end=449
  _globals['_SYNCRESPONSE']._serialized_start=451
  _globals['_SYNCRESPONSE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
